/*
 * This code was generated by ResXResourceManager.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* tslint:disable */

function formatString(template: string, args: any): string {
  let result = template;
  Object.entries(args).forEach(entry => {
    const key = entry[0];
    const replacement = `${entry[1]}`;
    const pattern = new RegExp('\\$\\{\\s*' + key + '\\s*\\}', 'gm');
    result = result.replace(pattern, replacement);
  });
  return result;
}

export class Resources {
  private MAINPAGE_WELCOME_TEMPLATE = "Welcome ${User}!";
  MAINPAGE_WELCOME = (args: { User: string }) => {
    return formatString(this.MAINPAGE_WELCOME_TEMPLATE, args);
  }
  MAINPAGE_APPNAME = "Localized App";
}

